### ISSUE TITLE
Unmatched field {"name":"queue","domain":"shortstr"}

### ISSUE THREAD

**Issue by gquintana** [FGRibreau/node-amqp-dsl#1]
This error occurs when running AMQP Tool on RabbitMQ 3.1.5 to export messages

```
node_modules\.bin\amqp-tool --host myhost --username quest --password xxx --queue myqueue --count 5000 --export myqueue.json

C:\Logiciels\nodejs\node_modules\amqp-tool\node_modules\amqp-dsl\node_modules\amqp\amqp.js:771
          throw new Error("Unmatched field " + JSON.stringify(field));
                ^
Error: Unmatched field {"name":"queue","domain":"shortstr"}
    at serializeFields (C:\Logiciels\nodejs\node_modules\amqp-tool\node_modules\amqp-dsl\node_modules\amqp\amqp.js:771:17)
    at Connection._sendMethod (C:\Logiciels\nodejs\node_modules\amqp-tool\node_modules\amqp-dsl\node_modules\amqp\amqp.js:1221:3)
    at Queue._onMethod (C:\Logiciels\nodejs\node_modules\amqp-tool\node_modules\amqp-dsl\node_modules\amqp\amqp.js:1915:25)
    at Queue.Channel._onChannelMethod (C:\Logiciels\nodejs\node_modules\amqp-tool\node_modules\amqp-dsl\node_modules\amqp\amqp.js:1557:14)
    at Connection._onMethod (C:\Logiciels\nodejs\node_modules\amqp-tool\node_modules\amqp-dsl\node_modules\amqp\amqp.js:1088:28)
    at AMQPParser.parser.onMethod (C:\Logiciels\nodejs\node_modules\amqp-tool\node_modules\amqp-dsl\node_modules\amqp\amqp.js:897:12)
    at AMQPParser._parseMethodFrame (C:\Logiciels\nodejs\node_modules\amqp-tool\node_modules\amqp-dsl\node_modules\amqp\amqp.js:451:10)
    at frameEnd (C:\Logiciels\nodejs\node_modules\amqp-tool\node_modules\amqp-dsl\node_modules\amqp\amqp.js:192:16)
    at frame (C:\Logiciels\nodejs\node_modules\amqp-tool\node_modules\amqp-dsl\node_modules\amqp\amqp.js:177:14)
    at AMQPParser.header [as parse] (C:\Logiciels\nodejs\node_modules\amqp-tool\node_modules\amqp-dsl\node_modules\amqp\amqp.js:163:14)
```

In the code, the Error is raised because typeof(param)='object'

```
      case 'shortstr':
        if (typeof(param) != "string" || param.length > 0xFF) {
          throw new Error("Unmatched field " + JSON.stringify(field));
        }
        serializeShortString(buffer, param);
        break;
```

**Comment by FGRibreau** [comment]
Hello again :)

It's definitely an issue with the underlying library `amqp`, try this:

``` shell
cd "C:\Logiciels\nodejs\node_modules\amqp-tool\node_modules\amqp-dsl\"
npm install amqp@0.1.7
```

and try to run the amqp-tool again. If it still does not work, just submit this issue to [node-amqp](https://github.com/postwait/node-amqp/issues?page=1&state=open).
